/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.45.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { AnyDataModel, DataModelFromSchemaDefinition } from "convex/server";
import type { GenericId } from "convex/values";
import type schema from "../schema.js";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = keyof DataModel;

/**
 * The type of a document stored in Convex.
 *
 * @typeParam TableName - A string matching a table name.
 */
export type Doc<TableName extends TableNames> = DataModel[TableName]["document"];

/**
 * An identifier for a document of type `TableName` in your Convex database.
 *
 * @typeParam TableName - A string matching a table name.
 */
export type Id<TableName extends TableNames | string = string> = GenericId<TableName>;

/**
 * A type describing your entire Convex data model, corresponding to the tables
 * in `convex/schema.ts`.
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
